% build_sgesvj_mex.m
openblas_lib = '/opt/homebrew/opt/openblas/lib';
gfortran_lib = '/opt/homebrew/Cellar/gcc/15.1.0/lib/gcc/15'

mex('-v','sgesvj_mex.c', ...
    ['-L' openblas_lib], '-lopenblas', ...
    ['-L' gfortran_lib], '-lgfortran', ...
    ['LDFLAGS=$LDFLAGS -Wl,-rpath,' openblas_lib ' -Wl,-rpath,' gfortran_lib]);
